# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/d/DevProjects/ConsoleCpp

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/d/DevProjects/ConsoleCpp

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/d/DevProjects/ConsoleCpp/CMakeFiles /mnt/d/DevProjects/ConsoleCpp//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/d/DevProjects/ConsoleCpp/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ConsoleCppApplication

# Build rule for target.
ConsoleCppApplication: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ConsoleCppApplication
.PHONY : ConsoleCppApplication

# fast build rule for target.
ConsoleCppApplication/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ConsoleCppApplication.dir/build.make CMakeFiles/ConsoleCppApplication.dir/build
.PHONY : ConsoleCppApplication/fast

#=============================================================================
# Target rules for targets named ConsoleCppStatic

# Build rule for target.
ConsoleCppStatic: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ConsoleCppStatic
.PHONY : ConsoleCppStatic

# fast build rule for target.
ConsoleCppStatic/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ConsoleCppStatic.dir/build.make CMakeFiles/ConsoleCppStatic.dir/build
.PHONY : ConsoleCppStatic/fast

#=============================================================================
# Target rules for targets named fmt

# Build rule for target.
fmt: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 fmt
.PHONY : fmt

# fast build rule for target.
fmt/fast:
	$(MAKE) $(MAKESILENT) -f 3rdparty/fmt/CMakeFiles/fmt.dir/build.make 3rdparty/fmt/CMakeFiles/fmt.dir/build
.PHONY : fmt/fast

example/Main.o: example/Main.cpp.o
.PHONY : example/Main.o

# target to build an object file
example/Main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ConsoleCppApplication.dir/build.make CMakeFiles/ConsoleCppApplication.dir/example/Main.cpp.o
.PHONY : example/Main.cpp.o

example/Main.i: example/Main.cpp.i
.PHONY : example/Main.i

# target to preprocess a source file
example/Main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ConsoleCppApplication.dir/build.make CMakeFiles/ConsoleCppApplication.dir/example/Main.cpp.i
.PHONY : example/Main.cpp.i

example/Main.s: example/Main.cpp.s
.PHONY : example/Main.s

# target to generate assembly for a file
example/Main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ConsoleCppApplication.dir/build.make CMakeFiles/ConsoleCppApplication.dir/example/Main.cpp.s
.PHONY : example/Main.cpp.s

src/BackgroundColor.o: src/BackgroundColor.cpp.o
.PHONY : src/BackgroundColor.o

# target to build an object file
src/BackgroundColor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ConsoleCppStatic.dir/build.make CMakeFiles/ConsoleCppStatic.dir/src/BackgroundColor.cpp.o
.PHONY : src/BackgroundColor.cpp.o

src/BackgroundColor.i: src/BackgroundColor.cpp.i
.PHONY : src/BackgroundColor.i

# target to preprocess a source file
src/BackgroundColor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ConsoleCppStatic.dir/build.make CMakeFiles/ConsoleCppStatic.dir/src/BackgroundColor.cpp.i
.PHONY : src/BackgroundColor.cpp.i

src/BackgroundColor.s: src/BackgroundColor.cpp.s
.PHONY : src/BackgroundColor.s

# target to generate assembly for a file
src/BackgroundColor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ConsoleCppStatic.dir/build.make CMakeFiles/ConsoleCppStatic.dir/src/BackgroundColor.cpp.s
.PHONY : src/BackgroundColor.cpp.s

src/ConsoleAttributes.o: src/ConsoleAttributes.cpp.o
.PHONY : src/ConsoleAttributes.o

# target to build an object file
src/ConsoleAttributes.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ConsoleCppStatic.dir/build.make CMakeFiles/ConsoleCppStatic.dir/src/ConsoleAttributes.cpp.o
.PHONY : src/ConsoleAttributes.cpp.o

src/ConsoleAttributes.i: src/ConsoleAttributes.cpp.i
.PHONY : src/ConsoleAttributes.i

# target to preprocess a source file
src/ConsoleAttributes.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ConsoleCppStatic.dir/build.make CMakeFiles/ConsoleCppStatic.dir/src/ConsoleAttributes.cpp.i
.PHONY : src/ConsoleAttributes.cpp.i

src/ConsoleAttributes.s: src/ConsoleAttributes.cpp.s
.PHONY : src/ConsoleAttributes.s

# target to generate assembly for a file
src/ConsoleAttributes.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ConsoleCppStatic.dir/build.make CMakeFiles/ConsoleCppStatic.dir/src/ConsoleAttributes.cpp.s
.PHONY : src/ConsoleAttributes.cpp.s

src/ConsoleMode.o: src/ConsoleMode.cpp.o
.PHONY : src/ConsoleMode.o

# target to build an object file
src/ConsoleMode.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ConsoleCppStatic.dir/build.make CMakeFiles/ConsoleCppStatic.dir/src/ConsoleMode.cpp.o
.PHONY : src/ConsoleMode.cpp.o

src/ConsoleMode.i: src/ConsoleMode.cpp.i
.PHONY : src/ConsoleMode.i

# target to preprocess a source file
src/ConsoleMode.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ConsoleCppStatic.dir/build.make CMakeFiles/ConsoleCppStatic.dir/src/ConsoleMode.cpp.i
.PHONY : src/ConsoleMode.cpp.i

src/ConsoleMode.s: src/ConsoleMode.cpp.s
.PHONY : src/ConsoleMode.s

# target to generate assembly for a file
src/ConsoleMode.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ConsoleCppStatic.dir/build.make CMakeFiles/ConsoleCppStatic.dir/src/ConsoleMode.cpp.s
.PHONY : src/ConsoleMode.cpp.s

src/DelimStyle.o: src/DelimStyle.cpp.o
.PHONY : src/DelimStyle.o

# target to build an object file
src/DelimStyle.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ConsoleCppStatic.dir/build.make CMakeFiles/ConsoleCppStatic.dir/src/DelimStyle.cpp.o
.PHONY : src/DelimStyle.cpp.o

src/DelimStyle.i: src/DelimStyle.cpp.i
.PHONY : src/DelimStyle.i

# target to preprocess a source file
src/DelimStyle.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ConsoleCppStatic.dir/build.make CMakeFiles/ConsoleCppStatic.dir/src/DelimStyle.cpp.i
.PHONY : src/DelimStyle.cpp.i

src/DelimStyle.s: src/DelimStyle.cpp.s
.PHONY : src/DelimStyle.s

# target to generate assembly for a file
src/DelimStyle.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ConsoleCppStatic.dir/build.make CMakeFiles/ConsoleCppStatic.dir/src/DelimStyle.cpp.s
.PHONY : src/DelimStyle.cpp.s

src/Font.o: src/Font.cpp.o
.PHONY : src/Font.o

# target to build an object file
src/Font.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ConsoleCppStatic.dir/build.make CMakeFiles/ConsoleCppStatic.dir/src/Font.cpp.o
.PHONY : src/Font.cpp.o

src/Font.i: src/Font.cpp.i
.PHONY : src/Font.i

# target to preprocess a source file
src/Font.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ConsoleCppStatic.dir/build.make CMakeFiles/ConsoleCppStatic.dir/src/Font.cpp.i
.PHONY : src/Font.cpp.i

src/Font.s: src/Font.cpp.s
.PHONY : src/Font.s

# target to generate assembly for a file
src/Font.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ConsoleCppStatic.dir/build.make CMakeFiles/ConsoleCppStatic.dir/src/Font.cpp.s
.PHONY : src/Font.cpp.s

src/ForegroundColor.o: src/ForegroundColor.cpp.o
.PHONY : src/ForegroundColor.o

# target to build an object file
src/ForegroundColor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ConsoleCppStatic.dir/build.make CMakeFiles/ConsoleCppStatic.dir/src/ForegroundColor.cpp.o
.PHONY : src/ForegroundColor.cpp.o

src/ForegroundColor.i: src/ForegroundColor.cpp.i
.PHONY : src/ForegroundColor.i

# target to preprocess a source file
src/ForegroundColor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ConsoleCppStatic.dir/build.make CMakeFiles/ConsoleCppStatic.dir/src/ForegroundColor.cpp.i
.PHONY : src/ForegroundColor.cpp.i

src/ForegroundColor.s: src/ForegroundColor.cpp.s
.PHONY : src/ForegroundColor.s

# target to generate assembly for a file
src/ForegroundColor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ConsoleCppStatic.dir/build.make CMakeFiles/ConsoleCppStatic.dir/src/ForegroundColor.cpp.s
.PHONY : src/ForegroundColor.cpp.s

src/PrintCxx17.o: src/PrintCxx17.cpp.o
.PHONY : src/PrintCxx17.o

# target to build an object file
src/PrintCxx17.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ConsoleCppStatic.dir/build.make CMakeFiles/ConsoleCppStatic.dir/src/PrintCxx17.cpp.o
.PHONY : src/PrintCxx17.cpp.o

src/PrintCxx17.i: src/PrintCxx17.cpp.i
.PHONY : src/PrintCxx17.i

# target to preprocess a source file
src/PrintCxx17.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ConsoleCppStatic.dir/build.make CMakeFiles/ConsoleCppStatic.dir/src/PrintCxx17.cpp.i
.PHONY : src/PrintCxx17.cpp.i

src/PrintCxx17.s: src/PrintCxx17.cpp.s
.PHONY : src/PrintCxx17.s

# target to generate assembly for a file
src/PrintCxx17.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ConsoleCppStatic.dir/build.make CMakeFiles/ConsoleCppStatic.dir/src/PrintCxx17.cpp.s
.PHONY : src/PrintCxx17.cpp.s

src/PrintMode.o: src/PrintMode.cpp.o
.PHONY : src/PrintMode.o

# target to build an object file
src/PrintMode.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ConsoleCppStatic.dir/build.make CMakeFiles/ConsoleCppStatic.dir/src/PrintMode.cpp.o
.PHONY : src/PrintMode.cpp.o

src/PrintMode.i: src/PrintMode.cpp.i
.PHONY : src/PrintMode.i

# target to preprocess a source file
src/PrintMode.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ConsoleCppStatic.dir/build.make CMakeFiles/ConsoleCppStatic.dir/src/PrintMode.cpp.i
.PHONY : src/PrintMode.cpp.i

src/PrintMode.s: src/PrintMode.cpp.s
.PHONY : src/PrintMode.s

# target to generate assembly for a file
src/PrintMode.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ConsoleCppStatic.dir/build.make CMakeFiles/ConsoleCppStatic.dir/src/PrintMode.cpp.s
.PHONY : src/PrintMode.cpp.s

src/UnixCode.o: src/UnixCode.cpp.o
.PHONY : src/UnixCode.o

# target to build an object file
src/UnixCode.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ConsoleCppStatic.dir/build.make CMakeFiles/ConsoleCppStatic.dir/src/UnixCode.cpp.o
.PHONY : src/UnixCode.cpp.o

src/UnixCode.i: src/UnixCode.cpp.i
.PHONY : src/UnixCode.i

# target to preprocess a source file
src/UnixCode.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ConsoleCppStatic.dir/build.make CMakeFiles/ConsoleCppStatic.dir/src/UnixCode.cpp.i
.PHONY : src/UnixCode.cpp.i

src/UnixCode.s: src/UnixCode.cpp.s
.PHONY : src/UnixCode.s

# target to generate assembly for a file
src/UnixCode.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ConsoleCppStatic.dir/build.make CMakeFiles/ConsoleCppStatic.dir/src/UnixCode.cpp.s
.PHONY : src/UnixCode.cpp.s

src/Utils.o: src/Utils.cpp.o
.PHONY : src/Utils.o

# target to build an object file
src/Utils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ConsoleCppStatic.dir/build.make CMakeFiles/ConsoleCppStatic.dir/src/Utils.cpp.o
.PHONY : src/Utils.cpp.o

src/Utils.i: src/Utils.cpp.i
.PHONY : src/Utils.i

# target to preprocess a source file
src/Utils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ConsoleCppStatic.dir/build.make CMakeFiles/ConsoleCppStatic.dir/src/Utils.cpp.i
.PHONY : src/Utils.cpp.i

src/Utils.s: src/Utils.cpp.s
.PHONY : src/Utils.s

# target to generate assembly for a file
src/Utils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ConsoleCppStatic.dir/build.make CMakeFiles/ConsoleCppStatic.dir/src/Utils.cpp.s
.PHONY : src/Utils.cpp.s

src/WindowConsole.o: src/WindowConsole.cpp.o
.PHONY : src/WindowConsole.o

# target to build an object file
src/WindowConsole.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ConsoleCppStatic.dir/build.make CMakeFiles/ConsoleCppStatic.dir/src/WindowConsole.cpp.o
.PHONY : src/WindowConsole.cpp.o

src/WindowConsole.i: src/WindowConsole.cpp.i
.PHONY : src/WindowConsole.i

# target to preprocess a source file
src/WindowConsole.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ConsoleCppStatic.dir/build.make CMakeFiles/ConsoleCppStatic.dir/src/WindowConsole.cpp.i
.PHONY : src/WindowConsole.cpp.i

src/WindowConsole.s: src/WindowConsole.cpp.s
.PHONY : src/WindowConsole.s

# target to generate assembly for a file
src/WindowConsole.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ConsoleCppStatic.dir/build.make CMakeFiles/ConsoleCppStatic.dir/src/WindowConsole.cpp.s
.PHONY : src/WindowConsole.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... ConsoleCppApplication"
	@echo "... ConsoleCppStatic"
	@echo "... fmt"
	@echo "... example/Main.o"
	@echo "... example/Main.i"
	@echo "... example/Main.s"
	@echo "... src/BackgroundColor.o"
	@echo "... src/BackgroundColor.i"
	@echo "... src/BackgroundColor.s"
	@echo "... src/ConsoleAttributes.o"
	@echo "... src/ConsoleAttributes.i"
	@echo "... src/ConsoleAttributes.s"
	@echo "... src/ConsoleMode.o"
	@echo "... src/ConsoleMode.i"
	@echo "... src/ConsoleMode.s"
	@echo "... src/DelimStyle.o"
	@echo "... src/DelimStyle.i"
	@echo "... src/DelimStyle.s"
	@echo "... src/Font.o"
	@echo "... src/Font.i"
	@echo "... src/Font.s"
	@echo "... src/ForegroundColor.o"
	@echo "... src/ForegroundColor.i"
	@echo "... src/ForegroundColor.s"
	@echo "... src/PrintCxx17.o"
	@echo "... src/PrintCxx17.i"
	@echo "... src/PrintCxx17.s"
	@echo "... src/PrintMode.o"
	@echo "... src/PrintMode.i"
	@echo "... src/PrintMode.s"
	@echo "... src/UnixCode.o"
	@echo "... src/UnixCode.i"
	@echo "... src/UnixCode.s"
	@echo "... src/Utils.o"
	@echo "... src/Utils.i"
	@echo "... src/Utils.s"
	@echo "... src/WindowConsole.o"
	@echo "... src/WindowConsole.i"
	@echo "... src/WindowConsole.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

